In [2]:
import numpy as np

from quantecon.markov import MarkovChain

In [3]:
alpha = 0.25
beta = 0.03

In [5]:
# Job finding with static probabilities
P = np.array([[1-alpha, alpha], [beta, 1-beta]])

In [7]:
mc_simple = MarkovChain(P)

In [9]:
mc_simple.stationary_distributions

array([[0.10714286, 0.89285714]])

In [10]:
alpha_high = 0.40
alpha_low = 0.20

beta_high = 0.01
beta_low = 0.05

In [13]:
P_high = np.array([[1-alpha_high, alpha_high], [beta_high, 1-beta_high]])

mc_high = MarkovChain(P_high)
mc_high.stationary_distributions

array([[0.02439024, 0.97560976]])

In [14]:
P_low = np.array([[1-alpha_low, alpha_low], [beta_low, 1-beta_low]])

mc_low = MarkovChain(P_low)
mc_low.stationary_distributions

array([[0.2, 0.8]])

In [15]:
P_ab = np.array([[0.9, 0.1], [0.1, 0.9]])

mc_ab = MarkovChain(P_ab)

mc_ab.stationary_distributions

array([[0.5, 0.5]])

In [17]:
# UL UH EL EH
big_P = np.array([
    [0.9*(1-alpha_low), 0.1*(1 - alpha_low), 0.9*alpha_low, 0.1*alpha_low],
    [0.1*(1 - alpha_high), 0.9*(1 - alpha_high), 0.1*alpha_high, 0.9*alpha_high],
    [0.9*beta_low, 0.1*beta_low, 0.9*(1 - beta_low), 0.1*(1 - beta_low)],
    [0.1*beta_high, 0.9*beta_high, 0.1*(1 - beta_high), 0.9*(1 - beta_high)]
])

In [18]:
mc_big = MarkovChain(big_P)

In [19]:
mc_big.stationary_distributions

array([[0.07567568, 0.02702703, 0.42432432, 0.47297297]])

In [34]:
ev = np.linalg.eig(big_P.T)[1][:, 1]

ev / ev.sum()

array([0.07567568, 0.02702703, 0.42432432, 0.47297297])

In [29]:
np.linalg.matrix_power(big_P.T, 1000)

array([[0.07567568, 0.07567568, 0.07567568, 0.07567568],
       [0.02702703, 0.02702703, 0.02702703, 0.02702703],
       [0.42432432, 0.42432432, 0.42432432, 0.42432432],
       [0.47297297, 0.47297297, 0.47297297, 0.47297297]])

In [22]:
big_P

array([[0.72 , 0.08 , 0.18 , 0.02 ],
       [0.06 , 0.54 , 0.04 , 0.36 ],
       [0.045, 0.005, 0.855, 0.095],
       [0.001, 0.009, 0.099, 0.891]])

In [24]:
np.kron(P_ab, P_low)

array([[0.72 , 0.18 , 0.08 , 0.02 ],
       [0.045, 0.855, 0.005, 0.095],
       [0.08 , 0.02 , 0.72 , 0.18 ],
       [0.005, 0.095, 0.045, 0.855]])